[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "14.17.0"

[context.production]
base = "/"

[context.branch-deploy]
base = "/"

[context.deploy-preview]
base = "/"
